version: '3'

volumes:
  pg_data_production:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:13.10
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: dauletnazar/kittygram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static_volume:/static
      - media_volume:/app/media/
  frontend:
    image: dauletnazar/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static_volume:/static
  gateway:
    image: dauletnazar/kittygram_gateway
    env_file: .env
    depends_on:
      - db
      - backend
      - frontend
    volumes:
      - static_volume:/static/
      - media_volume:/app/media/
    ports:
      - 9000:80